### ISSUE TITLE
KeyWord Research Ultra

### ISSUE THREAD

**Issue by NaSabbir** [XpertStack/SEO-Workplace#5]
> 02/11/2016, Wednesday
## Session Breakdown:
- Project describes
- Keyword Classification 
1. Product OR Service Keyword:
2. Brands keyword:
3. Modify Keyword:
4. Geographic Keyword:
5. B2B Keyword:

- Find local search/ general search trends via Google Trends
- 

## Resource:
- http://searchengineland.com/
- https://moz.com/

## Task:
- [ ] Class Review / Feedback: 5(five) Main Ideas about previous class via [Google form](https://goo.gl/forms/08xGcK4i5KOVmTEg1).

- [ ] Blog writing via [Medium](https://medium.com/seo-workplace)

- [ ]

**Comment by arif98741** [comment]
Peer1 Blog
https://medium.com/@srrifat9670/swot-3ff431bf9b78#.bxzm2n56w
